import streamlit as st

# 1. Security Check: Redirect if not logged in
if 'authenticated' not in st.session_state or not st.session_state['authenticated']:
    st.warning("Please login on the main page first.")
    st.stop()

# 2. Page Configuration
st.set_page_config(page_title="Biological Context", page_icon="🔬", layout="wide")

# 3. Content: The Virus & The Target
st.title("🔬 Biological Context: HIV-1 Protease")
st.markdown("---")

# Layout: Split into two columns for professional reading
col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.header("1. The Virus (HIV-1)")
    st.write("""
    **HIV-1** is a retrovirus that targets the body's immune system, specifically CD4 cells. 
    To replicate, the virus enters a host cell and forces it to produce long, non-functional 
    polyprotein chains (Gag and Gag-Pol).
    
    **The Problem:** These chains are like 'uncut' raw materials. To create a mature, 
    infectious virus particle, these chains must be precisely sliced into individual 
    functional proteins.
    """)
    st.info("💡 Without this 'slicing' process, the virus remains immature and cannot infect other cells.")

with col2:
    st.header("2. The Target (HIV-1 Protease)")
    st.write("""
    **The Molecular Scissors:** HIV-1 Protease is the enzyme responsible for this 
    critical cutting. It belongs to the aspartic protease family and functions as a homodimer.
    
    **Mechanism of Inhibition:** Our goal in drug discovery is to design a 'Protease Inhibitor' (PI). This is a molecule 
    that sits in the **Active Site** of the enzyme. By binding here, the molecule 'jams 
    the scissors,' preventing the enzyme from performing its function.
    """)

st.markdown("---")

# 4. Visualizing the Target
st.subheader("Structural Analysis: The Active Site")
c1, c2 = st.columns([2, 1])

with c1:
    # This acts as a placeholder for the actual protease image you'll use
    st.image("https://upload.wikimedia.org/wikipedia/commons/4/4d/Hiv_protease_1hsg.png", 
             caption="3D Structure of HIV-1 Protease (PDB ID: 1HSG) complexed with an inhibitor.",
             use_container_width=True)



with c2:
    st.success("### Project Objective")
    st.write("""
    Using **LSTM (Long Short-Term Memory)** neural networks, we have generated 
    novel chemical structures (SMILES) that are predicted to bind effectively 
    to this specific protease pocket.
    
    **Coming Next:**
    In the Discovery Engine, we will analyze the 8 lead candidates generated by the AI.
    """)
    
    if st.button("Go to Discovery Engine 🚀"):
        st.switch_page("pages/2_Discovery.py")